theme: jekyll-theme-cayman
kramdown:
  parse_block_html: true

permalink: pretty

url: "https://subhadipchowdhury.github.io/"
description: "Personal academic website of Subhadip Chowdhury: teaching, pedagogy, research, and mentoring."
  
exclude: ['deploy', 'stylesheet.scss']

defaults:

  - scope:
      path: ""
    values:
      robots: true

compress_html:
  clippings: all
  blanklines: true
