"""The paper version of a concept map, generated from the same data as the page.

A student who wants to work offline gets a PDF, and the point of generating it from
the map data rather than from a second hand-kept tex file is that the two cannot
drift: the arrows, the boxes, the inventory and the closing question all come from
one place.

Two deliberate departures from Dip's own Practice Worksheet 3, which this is
modelled on:

- **Every arrow is drawn the same way.** His worksheet distinguishes solid,
  dashed, double-headed and dotted, and says so in the instructions. On screen the
  style is hidden until the arrow is named, because on paper it gives away half of
  every answer. The PDF hides it too, so the paper exercise asks exactly what the
  page asks, and the instructions ask for the kind as part of each answer.
- **`workbook.cls` is not used**, because it is not in the repository or in the
  TeX Live tree. This is a standalone `article` with kpfonts, which is what Dip
  asked for.

The blank worksheet is what the site serves. The answer key is written next to the
tex under `tools/`, which `_config.yml` excludes, so publishing the key is a
deliberate act rather than a side effect.
"""

import pathlib
import re
import shutil
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[2]
TEX_DIR = ROOT / "tools" / "author" / "tex"
PDF_DIR = ROOT / "teaching" / "labs" / "maps"

PDFLATEX = shutil.which("pdflatex") or "/Library/TeX/texbin/pdflatex"

# The four things a student circles, in the same order as KIND_ORDER in
# maps/engine/map.js so the paper and the page offer the same choices in the same
# sequence. An arrow is a relationship and not always an implication, so none of
# these says "claims".
KIND_WORDS = ["gives", "fails", "both ways", "gives, other hypotheses"]

PREAMBLE = r"""\documentclass[11pt]{article}

% Generated by tools/author/maptex.py. Do not edit; edit the map's author script
% and run it again.

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[margin=0.85in]{geometry}
\usepackage{amsmath}
\usepackage{kpfonts}
\usepackage{tikz}
\usetikzlibrary{arrows.meta}
\usepackage{enumitem}
\usepackage{multicol}
\usepackage{xcolor}

\definecolor{maroon}{HTML}{800000}
\definecolor{inkgrey}{HTML}{4D4D4D}

% An explicit white page. Without it the page background is undefined, and a viewer
% or a converter that composites onto black renders the body text invisible.
\pagecolor{white}

\pagestyle{empty}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0.6em}

\newcommand{\heading}[1]{%
  \par\medskip{\large\bfseries\color{maroon} #1}\par\smallskip}

\tikzset{
  concept/.style={rectangle, draw=inkgrey, rounded corners=2pt,
    align=center, font=\footnotesize, inner sep=3pt, fill=white, line width=0.5pt},
  edgenum/.style={circle, fill=white, draw=inkgrey, inner sep=0pt,
    minimum size=11pt, font=\scriptsize\bfseries, line width=0.4pt},
  nlabel/.style={font=\tiny\bfseries, text=inkgrey, inner sep=1pt},
  % One style for every arrow on the blank sheet. Which of the four kinds it is is
  % part of the question, so the drawing must not answer it.
  arr/.style={-, thick, inkgrey},
  % On the answer key each kind is drawn as itself, so the kinds can be checked off
  % the picture as well as read off the list. No hyphens in these names: tikz reads
  % a hyphen in a style name as an arrow-tip spec.
  kindimplies/.style={-{Latex[length=2mm]}, thick, green!45!black},
  kindfails/.style={-{Latex[length=2mm]}, thick, dashed, red!65!black},
  kindequiv/.style={{Latex[length=2mm]}-{Latex[length=2mm]}, thick, blue!60!black},
  kindcaution/.style={-{Latex[length=2mm]}, thick, densely dotted, orange!75!black},
}
"""


def _tex_label(label):
    """A node label as tikz content. `\\n` in the data is a line break."""
    return r" \\ ".join(label.split("\n"))


# Only these tags, and only these. A general `<[^>]+>` ate the mathematics: in
# "converges if \(L < 1\), diverges if \(L > 1\)" the stretch from the first `<`
# to the next `>` looks exactly like a tag, and item O of the series map shipped
# reading "absolutely convergent if L1".
_TAG = re.compile(r"</?(?:strong|em|b|i|code|span|br)\s*/?>", re.I)


def _plain(text):
    """Drop the few HTML tags a definition might carry. The data holds LaTeX."""
    return _TAG.sub("", str(text))


def _diagram(data, solutions):
    lines = [r"\begin{tikzpicture}[>=Latex]"]

    for n in data["nodes"]:
        x, y = n["tikz"]
        lines.append(
            f"  \\node[concept] ({n['id']}) at ({x}, {y}) "
            f"{{{_tex_label(n['label'])}}};"
        )

    lines.append("")
    for n in data["nodes"]:
        lines.append(
            f"  \\node[nlabel, anchor=south east] at ({n['id']}.north west) "
            f"{{{n['letter']}}};"
        )

    lines.append("")
    for e in data["edges"]:
        # Exactly the curve the page draws: mapkit clipped both ends to the measured
        # boxes and worked out the control point from those, and handed all three
        # points over. Drawing from the node names and a bend instead gave a
        # different curve, and the badge then sat beside the arrow.
        style = ("kind" + e["kind"]) if solutions else "arr"
        (x0, y0), (cx, cy), (x1, y1) = e["draw"]
        lines.append(
            f"  \\draw[{style}] ({x0}, {y0}) .. controls ({cx}, {cy}) .. ({x1}, {y1});"
        )

    # The numbered badges are placed at a computed point rather than with tikz's
    # `pos=`, because `pos` walks the drawn path by arc length while the page walks
    # the Bezier by its parameter. On a strongly bent arrow the two land in visibly
    # different places, and in the first PDF that put badge 5 on top of badge 1.
    # mapkit works out the point once and both renderers use it.
    lines.append("")
    for e in data["edges"]:
        bx, by = e["badge_tikz"]
        lines.append(f"  \\node[edgenum] at ({bx:.2f}, {by:.2f}) {{{e['n']}}};")

    lines.append(r"\end{tikzpicture}")
    return "\n".join(lines)


def _answer_lines(data, solutions):
    out = [r"\begin{multicols}{2}",
           r"\begin{enumerate}[label=\textbf{\arabic*.}, itemsep=0.55em, leftmargin=1.8em]"]
    for e in data["edges"]:
        out.append(r"\item")
        if solutions:
            out.append(r"  {\scriptsize\bfseries\color{maroon} " +
                       KIND_WORDS[["implies", "fails", "equiv", "caution"].index(e["kind"])] +
                       r".}\ " + _plain(e["statement"]))
            out.append(r"  {\scriptsize\color{inkgrey} " + _plain(e["why"]) + r"\par}")
        else:
            out.append(r"  {\scriptsize\color{inkgrey} " +
                       r" \;/\; ".join(KIND_WORDS) + r"}\par\vspace{2pt}")
            out.append(r"  \dotfill\\[2pt]\dotfill")
    out.append(r"\end{enumerate}")
    out.append(r"\end{multicols}")
    return "\n".join(out)


def _document(data, solutions):
    title = data["title"]
    if solutions:
        title += ": answers"

    parts = [PREAMBLE, r"\begin{document}", "",
             r"{\LARGE\bfseries\color{maroon} " + title + r"}\par\medskip",
             r"{\color{inkgrey}\small " + data.get("course", "Math 163") +
             r" \quad\textbullet\quad Prof.\ Chowdhury}\par\bigskip", ""]

    # The instructions. Not the intro from the data: that one is addressed to
    # someone looking at a screen and tells them to click things.
    if solutions:
        parts.append(r"Every arrow, with the kind of relationship it is. On this copy "
                     r"each arrow is drawn in the style of its kind, so you can check "
                     r"the kinds off the picture as well as off the list.")
    else:
        parts.append(
            r"The next page has " + str(len(data["nodes"])) + r" ideas as boxes, with "
            + str(len(data["edges"])) + r" numbered arrows between them and nothing "
            r"written on any arrow. An arrow is a relationship between two ideas, and "
            r"not always an implication. Sometimes the first box gives you the second. "
            r"Sometimes it doesn't, and there's a counterexample. Sometimes each gives "
            r"the other. And sometimes it does give it, but on hypotheses you wouldn't "
            r"have guessed."
        )
        parts.append("")
        parts.append(
            r"For each arrow, circle which of those four it is, and describe the "
            r"relationship in one sentence. Name the theorem where there is one, and "
            r"say what goes wrong where there isn't."
        )
    parts.append("")

    parts.append(r"\heading{What each box means}")
    parts.append(r"\small")
    parts.append(r"\begin{enumerate}[label=\textbf{\Alph*.}, leftmargin=2.2em, itemsep=1pt]")
    for n in data["nodes"]:
        heading = _tex_label(n["label"]).replace(r" \\ ", " ")
        parts.append(r"\item \textbf{" + heading + r".} " + _plain(n["definition"]))
    parts.append(r"\end{enumerate}")
    parts.append(r"\normalsize")

    if data.get("benchmarks"):
        parts.append(r"\heading{Counterexamples and benchmarks}")
        parts.append(r"\small")
        parts.append(r"\begin{itemize}[leftmargin=1.4em, itemsep=1pt]")
        for b in data["benchmarks"]:
            parts.append(r"\item " + _plain(b))
        parts.append(r"\end{itemize}")
        parts.append(r"\normalsize")

    # The diagram gets a page to itself, centred. Left at the top of the page it
    # sat in the upper half with the lower half empty, which reads as a mistake.
    parts.append(r"\newpage")
    parts.append(r"\vspace*{\fill}")
    parts.append(r"\begin{center}")
    parts.append(_diagram(data, solutions))
    parts.append(r"\end{center}")
    if not solutions:
        parts.append(r"\begin{center}\small\color{inkgrey}")
        parts.append(r"Every arrow is drawn the same way on purpose. Deciding the kind "
                     r"is half of each answer.")
        parts.append(r"\end{center}")
    if solutions:
        parts.append(r"\begin{center}\small")
        parts.append(r"\textcolor{green!45!black}{\textbf{---\!\!\textgreater\ gives}} \quad "
                     r"\textcolor{red!65!black}{\textbf{--\,--\!\!\textgreater\ fails}} \quad "
                     r"\textcolor{blue!60!black}{\textbf{\textless\!\!---\!\!\textgreater\ both ways}} \quad "
                     r"\textcolor{orange!75!black}{\textbf{$\cdots$\!\!\textgreater\ other hypotheses}}")
        parts.append(r"\end{center}")
    parts.append(r"\vspace*{\fill}")
    parts.append(r"\newpage")

    parts.append(r"\heading{The arrows}")
    parts.append(r"\small")
    parts.append(_answer_lines(data, solutions))
    parts.append(r"\normalsize")

    parts.append(r"\heading{One last question}")
    parts.append(_plain(data["reflection"]))
    if not solutions:
        parts.append(r"\par\medskip\dotfill\\[4pt]\dotfill\\[4pt]\dotfill")

    parts.append("")
    parts.append(r"\vfill")
    parts.append(r"{\scriptsize\color{inkgrey} Contents by Subhadip Chowdhury, "
                 r"licensed CC BY-NC-SA 4.0. Built with AI assistance. I checked the "
                 r"mathematics myself.\par}")
    parts.append(r"\end{document}")
    return "\n".join(parts) + "\n"


def _compile(tex_path, out_dir):
    """Run pdflatex twice; multicols needs the second pass to balance."""
    out_dir.mkdir(parents=True, exist_ok=True)
    for _ in range(2):
        run = subprocess.run(
            [PDFLATEX, "-interaction=nonstopmode", "-halt-on-error",
             f"-output-directory={out_dir}", tex_path.name],
            cwd=tex_path.parent, capture_output=True, text=True,
        )
    if run.returncode != 0:
        tail = [ln for ln in run.stdout.splitlines() if ln.startswith("!")][:6]
        raise SystemExit(
            f"pdflatex failed on {tex_path.name}:\n  " + "\n  ".join(tail or ["see the log"])
        )
    return out_dir / (tex_path.stem + ".pdf")


def build(data):
    """Write both tex files, compile both, and put the blank PDF where the site is.

    The geometry arrives ready to draw: mapkit puts each arrow's three control
    points and its badge position into the edge, in tikz units.

    Returns the served path of the blank PDF, relative to the site root.
    """
    TEX_DIR.mkdir(parents=True, exist_ok=True)

    served = None
    for solutions in (False, True):
        stem = data["id"] + ("-solutions" if solutions else "")
        tex = TEX_DIR / f"{stem}.tex"
        tex.write_text(_document(data, solutions))
        pdf = _compile(tex, TEX_DIR)
        if not solutions:
            PDF_DIR.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(pdf, PDF_DIR / f"{data['id']}.pdf")
            served = f"/teaching/labs/maps/{data['id']}.pdf"

    return served
