"""The paper version of a concept map, generated from the same data as the page.

A student who wants to work offline gets a PDF, and the point of generating it from
the map data rather than from a second hand-kept tex file is that the two cannot
drift: the arrows, the boxes, the inventory and the closing question all come from
one place.

Two deliberate departures from Dip's own Practice Worksheet 3, which this is
modelled on:

- **Every arrow is drawn the same way.** His worksheet distinguishes solid,
  dashed, double-headed and dotted, and says so in the instructions. On screen the
  style is hidden until the arrow is named, because on paper it gives away half of
  every answer. The PDF hides it too, so the paper exercise asks exactly what the
  page asks, and the instructions ask for the kind as part of each answer.
- **`workbook.cls` is not used**, because it is not in the repository or in the
  TeX Live tree. This is a standalone `article` with kpfonts, which is what Dip
  asked for.

The blank worksheet is what the site serves. The answer key is written next to the
tex under `tools/`, which `_config.yml` excludes, so publishing the key is a
deliberate act rather than a side effect.
"""

import pathlib
import re
import shutil
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[2]
TEX_DIR = ROOT / "tools" / "author" / "tex"
PDF_DIR = ROOT / "teaching" / "labs" / "maps"

PDFLATEX = shutil.which("pdflatex") or "/Library/TeX/texbin/pdflatex"

# The four words a student circles. Kept in the same order as KIND_ORDER in
# maps/engine/map.js so the paper and the page offer the same four choices in the
# same sequence.
KIND_WORDS = ["holds", "fails", "equivalent", "other hypotheses"]

PREAMBLE = r"""\documentclass[11pt]{article}

% Generated by tools/author/maptex.py. Do not edit; edit the map's author script
% and run it again.

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[margin=0.85in]{geometry}
\usepackage{amsmath}
\usepackage{kpfonts}
\usepackage{tikz}
\usetikzlibrary{arrows.meta}
\usepackage{enumitem}
\usepackage{multicol}
\usepackage{xcolor}

\definecolor{maroon}{HTML}{800000}
\definecolor{inkgrey}{HTML}{4D4D4D}

\pagestyle{empty}
\setlength{\parindent}{0pt}

\newcommand{\heading}[1]{%
  \par\medskip{\large\bfseries\color{maroon} #1}\par\smallskip}

\tikzset{
  concept/.style={rectangle, draw=inkgrey, rounded corners=2pt,
    align=center, font=\footnotesize, inner sep=3pt, fill=white, line width=0.5pt},
  edgenum/.style={circle, fill=white, draw=inkgrey, inner sep=0pt,
    minimum size=11pt, font=\scriptsize\bfseries, line width=0.4pt},
  nlabel/.style={font=\tiny\bfseries, text=inkgrey, inner sep=1pt},
  % One style for every arrow. Which of the four kinds it is is part of the
  % question, so the drawing must not answer it.
  arr/.style={-, thick, inkgrey},
  solved/.style={-{Latex[length=2mm]}, thick, maroon},
}
"""


def _tex_label(label):
    """A node label as tikz content. `\\n` in the data is a line break."""
    return r" \\ ".join(label.split("\n"))


def _plain(text):
    """Strip the HTML a definition may carry. The data holds LaTeX, not markup."""
    return re.sub(r"<[^>]+>", "", str(text))


def _diagram(data, solutions):
    lines = [r"\begin{tikzpicture}[>=Latex]"]

    for n in data["nodes"]:
        x, y = n["tikz"]
        lines.append(
            f"  \\node[concept] ({n['id']}) at ({x}, {y}) "
            f"{{{_tex_label(n['label'])}}};"
        )

    lines.append("")
    for n in data["nodes"]:
        lines.append(
            f"  \\node[nlabel, anchor=south east] at ({n['id']}.north west) "
            f"{{{n['letter']}}};"
        )

    lines.append("")
    for e in data["edges"]:
        # The same quadratic the page draws, so the paper and the screen have the
        # same shape. bend is a pixel offset there; SCALE converts it back.
        style = "solved" if solutions else "arr"
        cx, cy = e["control"]
        lines.append(
            f"  \\draw[{style}] ({e['from']}) .. controls ({cx:.2f}, {cy:.2f}) .. "
            f"({e['to']});"
        )

    # The numbered badges are placed at a computed point rather than with tikz's
    # `pos=`, because `pos` walks the drawn path by arc length while the page walks
    # the Bezier by its parameter. On a strongly bent arrow the two land in visibly
    # different places, and in the first PDF that put badge 5 on top of badge 1.
    # mapkit works out the point once and both renderers use it.
    lines.append("")
    for e in data["edges"]:
        bx, by = e["badge_tikz"]
        lines.append(f"  \\node[edgenum] at ({bx:.2f}, {by:.2f}) {{{e['n']}}};")

    lines.append(r"\end{tikzpicture}")
    return "\n".join(lines)


def _answer_lines(data, solutions):
    out = [r"\begin{multicols}{2}",
           r"\begin{enumerate}[label=\textbf{\arabic*.}, itemsep=0.55em, leftmargin=1.8em]"]
    for e in data["edges"]:
        out.append(r"\item")
        if solutions:
            out.append(r"  {\scriptsize\bfseries\color{maroon} " +
                       KIND_WORDS[["implies", "fails", "equiv", "caution"].index(e["kind"])] +
                       r".}\ " + _plain(e["statement"]))
        else:
            out.append(r"  {\scriptsize\color{inkgrey} " +
                       r" \;/\; ".join(KIND_WORDS) + r"}\par\vspace{2pt}")
            out.append(r"  \dotfill\\[2pt]\dotfill")
    out.append(r"\end{enumerate}")
    out.append(r"\end{multicols}")
    return "\n".join(out)


def _document(data, solutions):
    title = data["title"]
    if solutions:
        title += ": answers"

    parts = [PREAMBLE, r"\begin{document}", "",
             r"{\LARGE\bfseries\color{maroon} " + title + r"}\par\medskip",
             r"{\color{inkgrey}\small Math 163 \quad\textbullet\quad Prof.\ Chowdhury"
             r" \quad\textbullet\quad Concept map}\par\bigskip", ""]

    # The instructions. Not the intro from the data: that one is addressed to
    # someone looking at a screen and tells them to click things.
    if solutions:
        parts.append(r"Every arrow named, with the kind of relationship it is. "
                     r"The arrows are drawn here in one style, as they are on the "
                     r"blank worksheet and on the web version.")
    else:
        parts.append(
            r"The next page shows " + str(len(data["nodes"])) + r" ideas as labelled "
            r"boxes, joined by " + str(len(data["edges"])) + r" numbered arrows. "
            r"Every arrow is a real mathematical relationship, and the drawing does "
            r"not tell you which kind: an arrow may \emph{hold}, it may \emph{fail}, "
            r"the two ideas may be \emph{equivalent}, or it may hold on "
            r"\emph{other hypotheses} than the ones its neighbours use. "
            r"For each numbered arrow, circle the kind and describe the relationship "
            r"in one sentence. Name the theorem, state the hypothesis that is doing "
            r"the work, or say what goes wrong."
        )
    parts.append("")

    parts.append(r"\heading{What each box means}")
    parts.append(r"\small")
    parts.append(r"\begin{enumerate}[label=\textbf{\Alph*.}, leftmargin=2.2em, itemsep=1pt]")
    for n in data["nodes"]:
        heading = _tex_label(n["label"]).replace(r" \\ ", " ")
        parts.append(r"\item \textbf{" + heading + r".} " + _plain(n["definition"]))
    parts.append(r"\end{enumerate}")
    parts.append(r"\normalsize")

    if data.get("benchmarks"):
        parts.append(r"\heading{Examples worth keeping to hand}")
        parts.append(r"\small")
        parts.append(r"\begin{itemize}[leftmargin=1.4em, itemsep=1pt]")
        for b in data["benchmarks"]:
            parts.append(r"\item " + _plain(b))
        parts.append(r"\end{itemize}")
        parts.append(r"\normalsize")

    # The diagram gets a page to itself, centred. Left at the top of the page it
    # sat in the upper half with the lower half empty, which reads as a mistake.
    parts.append(r"\newpage")
    parts.append(r"\vspace*{\fill}")
    parts.append(r"\begin{center}")
    parts.append(_diagram(data, solutions))
    parts.append(r"\end{center}")
    if not solutions:
        parts.append(r"\begin{center}\small\color{inkgrey}")
        parts.append(r"Every arrow is drawn the same way. For each one, decide "
                     r"whether it holds, fails, is an equivalence, or holds on other "
                     r"hypotheses, and say what it claims.")
        parts.append(r"\end{center}")
    parts.append(r"\vspace*{\fill}")
    parts.append(r"\newpage")

    parts.append(r"\heading{The arrows}")
    parts.append(r"\small")
    parts.append(_answer_lines(data, solutions))
    parts.append(r"\normalsize")

    parts.append(r"\heading{One last question}")
    parts.append(_plain(data["reflection"]))
    if not solutions:
        parts.append(r"\par\medskip\dotfill\\[4pt]\dotfill\\[4pt]\dotfill")

    parts.append("")
    parts.append(r"\vfill")
    parts.append(r"{\scriptsize\color{inkgrey} Contents by Subhadip Chowdhury, "
                 r"licensed CC BY-NC-SA 4.0. Built with AI assistance; the "
                 r"mathematics was checked by a human.\par}")
    parts.append(r"\end{document}")
    return "\n".join(parts) + "\n"


def _compile(tex_path, out_dir):
    """Run pdflatex twice; multicols needs the second pass to balance."""
    out_dir.mkdir(parents=True, exist_ok=True)
    for _ in range(2):
        run = subprocess.run(
            [PDFLATEX, "-interaction=nonstopmode", "-halt-on-error",
             f"-output-directory={out_dir}", tex_path.name],
            cwd=tex_path.parent, capture_output=True, text=True,
        )
    if run.returncode != 0:
        tail = [ln for ln in run.stdout.splitlines() if ln.startswith("!")][:6]
        raise SystemExit(
            f"pdflatex failed on {tex_path.name}:\n  " + "\n  ".join(tail or ["see the log"])
        )
    return out_dir / (tex_path.stem + ".pdf")


def build(data, scale):
    """Write both tex files, compile both, and put the blank PDF where the site is.

    `scale` is `mapkit.SCALE`, needed to turn a pixel bend back into tikz units.
    Returns the served path of the blank PDF, relative to the site root.
    """
    TEX_DIR.mkdir(parents=True, exist_ok=True)

    # The control point of each arrow, in tikz units, from the same construction
    # the engine uses. Done here rather than in the template so the arithmetic
    # sits next to the comment explaining it.
    for e in data["edges"]:
        a = next(n for n in data["nodes"] if n["id"] == e["from"])["tikz"]
        b = next(n for n in data["nodes"] if n["id"] == e["to"])["tikz"]
        mx, my = (a[0] + b[0]) / 2, (a[1] + b[1]) / 2
        bend = e.get("bend", 0) / scale
        if bend:
            dx, dy = b[0] - a[0], b[1] - a[1]
            length = (dx * dx + dy * dy) ** 0.5 or 1
            # y runs upward in tikz and downward on the stage. Mirroring the curve
            # in y means negating the y component of the offset, and dy has already
            # changed sign with the axis, so the x component keeps its form and the
            # y component gains a minus against controlPoint() in map.js. Getting
            # this wrong bows every curved arrow the opposite way, which is what the
            # first PDF did.
            mx, my = mx + dy / length * bend, my - dx / length * bend
        e["control"] = (mx, my)

    served = None
    for solutions in (False, True):
        stem = data["id"] + ("-solutions" if solutions else "")
        tex = TEX_DIR / f"{stem}.tex"
        tex.write_text(_document(data, solutions))
        pdf = _compile(tex, TEX_DIR)
        if not solutions:
            PDF_DIR.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(pdf, PDF_DIR / f"{data['id']}.pdf")
            served = f"/teaching/labs/maps/{data['id']}.pdf"

    for e in data["edges"]:
        del e["control"]

    return served
