"""The paper version of a concept map, generated from the same data as the page.

A student who wants to work offline gets a PDF, and the point of generating it from
the map data rather than from a second hand-kept tex file is that the two cannot
drift: the arrows, the boxes, the inventory and the closing question all come from
one place.

**The worksheet is the primary artefact.** As of 2026-08-13 the page is a checker: it
draws the map, reveals one arrow at a time, and keeps the whole answer list behind a
toggle. The work happens on paper, so the worksheet says so and carries the address of
the page.

Arrows are drawn identically here and on the key, heads and all, with a head at each
end where the relationship runs both ways. There is nothing left to withhold: the
kind question is gone and every arrow holds in the direction drawn.

`workbook.cls` is not used, because it is not in the repository or in the TeX Live
tree. This is a standalone `article` with kpfonts, which is what Dip asked for.

The blank worksheet is what the site serves. The answer key is written next to the
tex under `tools/`, which `_config.yml` excludes, so publishing the key is a
deliberate act rather than a side effect.
"""

import pathlib
import re
import shutil
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[2]
TEX_DIR = ROOT / "tools" / "author" / "tex"
PDF_DIR = ROOT / "teaching" / "labs" / "worksheets"

PDFLATEX = shutil.which("pdflatex") or "/Library/TeX/texbin/pdflatex"

# Where the site serves the maps. Printed on the worksheet so a student holding
# paper can find the page that checks it.
PAGE_URL = "subhadipchowdhury.github.io/teaching/labs/maps"

PREAMBLE = r"""\documentclass[11pt]{article}

% Generated by tools/author/maptex.py. Do not edit; edit the map's author script
% and run it again.

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[margin=0.85in]{geometry}
\usepackage{amsmath}
\usepackage{kpfonts}
\usepackage{tikz}
\usetikzlibrary{arrows.meta}
\usepackage{enumitem}
\usepackage{multicol}
\usepackage{xcolor}
\usepackage{url}

\definecolor{maroon}{HTML}{800000}
\definecolor{inkgrey}{HTML}{4D4D4D}

% An explicit white page. Without it the page background is undefined, and a viewer
% or a converter that composites onto black renders the body text invisible.
\pagecolor{white}

\pagestyle{empty}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0.6em}

\newcommand{\heading}[1]{%
  \par\medskip{\large\bfseries\color{maroon} #1}\par\smallskip}

\tikzset{
  concept/.style={rectangle, draw=inkgrey, rounded corners=2pt,
    align=center, font=\footnotesize, inner sep=3pt, fill=white, line width=0.5pt},
  edgenum/.style={circle, fill=white, draw=inkgrey, inner sep=0pt,
    minimum size=11pt, font=\scriptsize\bfseries, line width=0.4pt},
  nlabel/.style={font=\tiny\bfseries, text=inkgrey, inner sep=1pt},
  % One arrow style, on the worksheet and on the key alike. Nothing is withheld any
  % more, so the head is drawn, and a relationship that runs both ways gets two of
  % them. No hyphens in these names: tikz reads a hyphen as an arrow-tip spec.
  kindholds/.style={-{Latex[length=2mm]}, thick, inkgrey},
  kindequiv/.style={{Latex[length=2mm]}-{Latex[length=2mm]}, thick, inkgrey},
}
"""


def _tex_label(label):
    """A node label as tikz content. `\\n` in the data is a line break."""
    return r" \\ ".join(label.split("\n"))


# Only these tags, and only these. A general `<[^>]+>` ate the mathematics: in
# "converges if \(L < 1\), diverges if \(L > 1\)" the stretch from the first `<`
# to the next `>` looks exactly like a tag, and item O of the series map shipped
# reading "absolutely convergent if L1".
_TAG = re.compile(r"</?(?:strong|em|b|i|code|span|br)\s*/?>", re.I)


def _plain(text):
    """Drop the few HTML tags a definition might carry. The data holds LaTeX."""
    return _TAG.sub("", str(text))


def _diagram(data, solutions):
    lines = [r"\begin{tikzpicture}[>=Latex]"]

    for n in data["nodes"]:
        x, y = n["tikz"]
        lines.append(
            f"  \\node[concept] ({n['id']}) at ({x}, {y}) "
            f"{{{_tex_label(n['label'])}}};"
        )

    lines.append("")
    for n in data["nodes"]:
        lines.append(
            f"  \\node[nlabel, anchor=south east] at ({n['id']}.north west) "
            f"{{{n['letter']}}};"
        )

    lines.append("")
    for e in data["edges"]:
        # Exactly the curve the page draws: mapkit clipped both ends to the measured
        # boxes and worked out the control point from those, and handed all three
        # points over. Drawing from the node names and a bend instead gave a
        # different curve, and the badge then sat beside the arrow.
        style = "kind" + e["kind"]
        (x0, y0), (cx, cy), (x1, y1) = e["draw"]
        lines.append(
            f"  \\draw[{style}] ({x0}, {y0}) .. controls ({cx}, {cy}) .. ({x1}, {y1});"
        )

    # The numbered badges are placed at a computed point rather than with tikz's
    # `pos=`, because `pos` walks the drawn path by arc length while the page walks
    # the Bezier by its parameter. On a strongly bent arrow the two land in visibly
    # different places, and in the first PDF that put badge 5 on top of badge 1.
    # mapkit works out the point once and both renderers use it.
    lines.append("")
    for e in data["edges"]:
        bx, by = e["badge_tikz"]
        lines.append(f"  \\node[edgenum] at ({bx:.2f}, {by:.2f}) {{{e['n']}}};")

    lines.append(r"\end{tikzpicture}")
    return "\n".join(lines)


def _answer_lines(data, solutions):
    """Two ruled lines per arrow on the worksheet; the sentence and its reason on
    the key. There is no kind to circle any more, so the room goes to writing."""
    out = [r"\begin{multicols}{2}",
           r"\begin{enumerate}[label=\textbf{\arabic*.}, itemsep=0.7em, leftmargin=1.8em]"]
    for e in data["edges"]:
        out.append(r"\item")
        if solutions:
            out.append("  " + _plain(e["statement"]))
            out.append(r"  {\scriptsize\color{inkgrey} " + _plain(e["why"]) + r"\par}")
        else:
            out.append(r"  \dotfill\\[3pt]\dotfill")
    out.append(r"\end{enumerate}")
    out.append(r"\end{multicols}")
    return "\n".join(out)


def _document(data, solutions):
    title = data["title"]
    if solutions:
        title += ": answers"

    parts = [PREAMBLE, r"\begin{document}", "",
             r"{\LARGE\bfseries\color{maroon} " + title + r"}\par\medskip",
             r"{\color{inkgrey}\small " + data.get("course", "Math 163") +
             r" \quad\textbullet\quad Prof.\ Chowdhury}\par\bigskip", ""]

    # The instructions. Not the intro from the data: that one is addressed to
    # someone looking at a screen and tells them to click things.
    if solutions:
        parts.append(r"Every arrow, with the reason underneath. Keep this away from the "
                     r"blank worksheet.")
    else:
        parts.append(
            r"The next page has " + str(len(data["nodes"])) + r" ideas as boxes, with "
            + str(len(data["edges"])) + r" numbered arrows between them and nothing "
            r"written on any arrow. Each arrow is a relationship that holds in the "
            r"direction drawn. Some are implications between properties. Some record "
            r"that one box is defined in terms of another. Many name the theorem that "
            r"decides a question about the box the arrow points at: the integral test "
            r"applied to \(1/x^p\) determines exactly which exponents make "
            r"\(\sum 1/n^p\) converge."
        )
        parts.append("")
        parts.append(
            r"For each numbered arrow, state the relationship in one sentence. Name the "
            r"theorem where there is one, and give the hypothesis it turns on. An arrow "
            r"with a head at each end holds in both directions."
        )
        parts.append("")
        parts.append(
            r"When you have had a go at all of them, check yourself at \url{" +
            PAGE_URL + "/" + data["id"] + r"/}. That page draws the same map and will "
            r"show you the answers one arrow at a time, or all at once."
        )
    parts.append("")

    parts.append(r"\heading{What each box means}")
    parts.append(r"\small")
    parts.append(r"\begin{enumerate}[label=\textbf{\Alph*.}, leftmargin=2.2em, itemsep=1pt]")
    for n in data["nodes"]:
        heading = _tex_label(n["label"]).replace(r" \\ ", " ")
        parts.append(r"\item \textbf{" + heading + r".} " + _plain(n["definition"]))
    parts.append(r"\end{enumerate}")
    parts.append(r"\normalsize")

    # The diagram gets a page to itself, centred. Left at the top of the page it
    # sat in the upper half with the lower half empty, which reads as a mistake.
    parts.append(r"\newpage")
    parts.append(r"\vspace*{\fill}")
    parts.append(r"\begin{center}")
    parts.append(_diagram(data, solutions))
    parts.append(r"\end{center}")
    parts.append(r"\vspace*{\fill}")
    parts.append(r"\newpage")

    parts.append(r"\heading{The arrows}")
    parts.append(r"\small")
    parts.append(_answer_lines(data, solutions))
    parts.append(r"\normalsize")

    if solutions and data.get("mistakes"):
        parts.append(r"\heading{Claims that look right and are not}")
        parts.append(r"\small")
        parts.append(r"\begin{itemize}[leftmargin=1.4em, itemsep=1pt]")
        for m in data["mistakes"]:
            parts.append(r"\item " + _plain(m))
        parts.append(r"\end{itemize}")
        parts.append(r"\normalsize")

    if data.get("benchmarks"):
        parts.append(r"\heading{Counterexamples and benchmarks}")
        parts.append(r"\small")
        parts.append(r"\begin{itemize}[leftmargin=1.4em, itemsep=1pt]")
        for b in data["benchmarks"]:
            parts.append(r"\item " + _plain(b))
        parts.append(r"\end{itemize}")
        parts.append(r"\normalsize")

    parts.append(r"\heading{One last question}")
    parts.append(_plain(data["reflection"]))
    if not solutions:
        parts.append(r"\par\medskip\dotfill\\[4pt]\dotfill\\[4pt]\dotfill")

    parts.append("")
    parts.append(r"\vfill")
    parts.append(r"{\scriptsize\color{inkgrey} Contents by Subhadip Chowdhury, "
                 r"licensed CC BY-NC-SA 4.0. Built with AI assistance. I checked the "
                 r"mathematics myself.\par}")
    parts.append(r"\end{document}")
    return "\n".join(parts) + "\n"


def _compile(tex_path, out_dir):
    """Run pdflatex twice; multicols needs the second pass to balance."""
    out_dir.mkdir(parents=True, exist_ok=True)
    for _ in range(2):
        run = subprocess.run(
            [PDFLATEX, "-interaction=nonstopmode", "-halt-on-error",
             f"-output-directory={out_dir}", tex_path.name],
            cwd=tex_path.parent, capture_output=True, text=True,
        )
    if run.returncode != 0:
        tail = [ln for ln in run.stdout.splitlines() if ln.startswith("!")][:6]
        raise SystemExit(
            f"pdflatex failed on {tex_path.name}:\n  " + "\n  ".join(tail or ["see the log"])
        )
    return out_dir / (tex_path.stem + ".pdf")


def build(data):
    """Write both tex files, compile both, and put the blank PDF where the site is.

    The geometry arrives ready to draw: mapkit puts each arrow's three control
    points and its badge position into the edge, in tikz units.

    Returns the served path of the blank PDF, relative to the site root.
    """
    TEX_DIR.mkdir(parents=True, exist_ok=True)

    served = None
    for solutions in (False, True):
        stem = data["id"] + ("-solutions" if solutions else "")
        tex = TEX_DIR / f"{stem}.tex"
        tex.write_text(_document(data, solutions))
        pdf = _compile(tex, TEX_DIR)
        if not solutions:
            PDF_DIR.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(pdf, PDF_DIR / f"{data['id']}.pdf")
            served = f"/teaching/labs/worksheets/{data['id']}.pdf"

    return served
